name: Build and Deploy
on:
  push:
    branches:
      - master
      - fix/action
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NPM Install
        uses: bahmutov/npm-install@v1.6.0
        with:
          install-command: npm ci --legacy-peer-deps
      - name: Build
        run: npm run prod
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: master
          build_dir: dist/ngx-echarts-starter
          keep_history: false
          allow_empty_commit: true
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}