name: Build and Deploy

on:
  push:
    branches:
      - master  
      - fix/action

jobs:
  build_and_deploy: 

    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Install NPM Dependencies
        uses: bahmutov/npm-install@v1.6.0  
        with:
          install-command: npm ci --legacy-peer-deps

      - name: Build Angular Project
        run: npm run prod

      - name: Deploy to GitHub Pages
        if: success() 
        uses: crazy-max/ghaction-git
        with:
          target_branch: gh-pages
          build_dir: dist/ngx-echarts-starter  
          keep_history: false
          allow_empty_commit: true
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  
